"""Seed data for Model Providers and Model Catalog."""

PROVIDERS_SEED = [
    {
        "id": "agentrouter",
        "site_name": "AgentRouter",
        "api_source": "agentrouter",
        "base_url": "https://agentrouter.org/v1",
        "api_key_env": "AGENTROUTER_API_KEY",
        "provider_type": "cloud",
        "quota_mode": "ONE_TIME_CREDIT",
        "supports_openai_compatible": True,
        "supports_model_discovery": False,
        "enabled": False,
        "priority": 10,
        "notes": "Credit dùng một lần. Bật enabled sau khi user nhập key và verify endpoint thực tế."
    },
    {
        "id": "bluesminds",
        "site_name": "BluesMinds",
        "api_source": "bluesminds",
        "base_url": "https://api.bluesminds.com/v1",
        "api_key_env": "BLUESMINDS_API_KEY",
        "provider_type": "cloud",
        "quota_mode": "ONE_TIME_CREDIT",
        "supports_openai_compatible": True,
        "supports_model_discovery": True,
        "models_endpoint": "/models",
        "chat_endpoint": "/chat/completions",
        "enabled": True,
        "priority": 20,
        "notes": "Unified LLM API gateway; credit-based. Treat quota as balance/credit."
    },
    {
        "id": "zenmux",
        "site_name": "ZenMux PAYG",
        "api_source": "zenmux",
        "base_url": "https://api.zenmux.ai/v1",
        "management_base_url": "https://zenmux.ai/api/platform",
        "api_key_env": "ZENMUX_API_KEY",
        "management_api_key_env": "ZENMUX_MANAGEMENT_API_KEY",
        "provider_type": "cloud",
        "quota_mode": "TOKEN_BUDGET",
        "supports_openai_compatible": True,
        "supports_model_discovery": True,
        "models_endpoint": "/models",
        "chat_endpoint": "/chat/completions",
        "enabled": True,
        "priority": 40,
        "notes": "PAYG/subscription. Use management API for balance/usage/subscription if key exists."
    },
    {
        "id": "mistral",
        "site_name": "Mistral.ai",
        "api_source": "mistral",
        "base_url": "https://api.mistral.ai/v1",
        "api_key_env": "MISTRAL_API_KEY",
        "provider_type": "cloud",
        "quota_mode": "TOKEN_BUDGET",
        "supports_openai_compatible": True,
        "supports_model_discovery": True,
        "models_endpoint": "/models",
        "chat_endpoint": "/chat/completions",
        "enabled": True,
        "priority": 60,
        "notes": "Limits include RPS, tokens per minute, and tokens per month depending on plan."
    },
    {
        "id": "nararouter",
        "site_name": "NaraRouter",
        "api_source": "nararouter",
        "base_url": "https://router.bynara.id/v1",
        "api_key_env": "NARAROUTER_API_KEY",
        "provider_type": "cloud",
        "quota_mode": "TOKEN_BUDGET",
        "supports_openai_compatible": True,
        "supports_model_discovery": True,
        "models_endpoint": "/models",
        "chat_endpoint": "/chat/completions",
        "enabled": True,
        "priority": 30,
        "notes": "Daily token budget provider. Treat as token/day reset provider."
    },
    {
        "id": "openrouter",
        "site_name": "OpenRouter",
        "api_source": "openrouter",
        "base_url": "https://openrouter.ai/api/v1",
        "api_key_env": "OPENROUTER_API_KEY",
        "provider_type": "cloud",
        "quota_mode": "RPM_RPD",
        "supports_openai_compatible": True,
        "supports_model_discovery": True,
        "models_endpoint": "/models",
        "chat_endpoint": "/chat/completions",
        "enabled": True,
        "priority": 50,
        "notes": "Free models end with :free. Free quota: RPM/RPD. Keep credit-aware metadata because purchased credits can raise free RPD."
    },
    {
        "id": "nvidia_nim",
        "site_name": "NVIDIA NIM",
        "api_source": "nvidia",
        "base_url": "https://integrate.api.nvidia.com/v1",
        "api_key_env": "NVIDIA_API_KEY",
        "provider_type": "cloud",
        "quota_mode": "RPM_RPD",
        "supports_openai_compatible": True,
        "supports_model_discovery": True,
        "models_endpoint": "/models",
        "chat_endpoint": "/chat/completions",
        "enabled": True,
        "priority": 70,
        "notes": "Rate limits may vary by model/use-case/traffic. Do not hardcode fixed global quota."
    },
    {
        "id": "google_ai_studio",
        "site_name": "Google AI Studio",
        "api_source": "google",
        "base_url": "https://generativelanguage.googleapis.com",
        "api_key_env": "GOOGLE_AI_STUDIO_API_KEY",
        "provider_type": "cloud",
        "quota_mode": "RPM_RPD",
        "supports_openai_compatible": False,
        "supports_model_discovery": True,
        "models_endpoint": "/v1beta/models",
        "enabled": True,
        "priority": 80,
        "notes": "Gemini quota uses RPM, TPM, and RPD. Client is not pure OpenAI-compatible unless using compatibility layer."
    },
    {
        "id": "ollama",
        "site_name": "Ollama (Local)",
        "api_source": "ollama",
        "base_url": "http://localhost:11434",
        "provider_type": "local",
        "quota_mode": "LOCAL_RESOURCE",
        "supports_openai_compatible": True,
        "supports_model_discovery": True,
        "models_endpoint": "/api/tags",
        "enabled": True,
        "priority": 100,
        "notes": "Chạy cục bộ trên máy người dùng, sử dụng tài nguyên phần cứng (CPU/GPU/VRAM)."
    }
]

MODELS_SEED = [
    # OpenRouter
    {
        "id": "openrouter_free",
        "provider_id": "openrouter",
        "model_id": "openrouter/free",
        "display_name": "OpenRouter Free Router",
        "type": "API",
        "billing_mode": "RPM_RPD",
        "context_window": 8192,
        "max_output_tokens": 4096,
        "capabilities": ["chat", "routing", "fallback"],
        "tags": ["Free", "Router", "General"],
        "default_roles": ["Fallback", "General Chat"],
        "description": "Free general routing model via OpenRouter.",
        "deployment": "Cloud API",
        "enabled": False
    },
    {
        "id": "deepseek_r1_free",
        "provider_id": "openrouter",
        "model_id": "deepseek/deepseek-r1:free",
        "display_name": "DeepSeek R1 Free",
        "type": "API",
        "billing_mode": "RPM_RPD",
        "context_window": 16384,
        "max_output_tokens": 8192,
        "capabilities": ["reasoning", "research", "planning"],
        "tags": ["Free", "Reasoning", "Research"],
        "default_roles": ["Researcher", "Reasoner"],
        "description": "Free reasoning model via OpenRouter. Verify availability before routing.",
        "deployment": "Cloud API",
        "enabled": False
    },
    {
        "id": "deepseek_chat_free",
        "provider_id": "openrouter",
        "model_id": "deepseek/deepseek-chat:free",
        "display_name": "DeepSeek Chat Free",
        "type": "API",
        "billing_mode": "RPM_RPD",
        "context_window": 8192,
        "max_output_tokens": 4096,
        "capabilities": ["chat", "coding", "planning"],
        "tags": ["Free", "Chat", "Coding"],
        "default_roles": ["Planner", "General Chat"],
        "description": "Free DeepSeek general chat/coding model via OpenRouter.",
        "deployment": "Cloud API",
        "enabled": False
    },
    {
        "id": "qwen_coder_free",
        "provider_id": "openrouter",
        "model_id": "qwen/qwen-coder:free",
        "display_name": "Qwen Coder Free",
        "type": "API",
        "billing_mode": "RPM_RPD",
        "context_window": 8192,
        "max_output_tokens": 4096,
        "capabilities": ["coding", "tool_use"],
        "tags": ["Free", "Coding", "Fast"],
        "default_roles": ["Coder", "Tool Use"],
        "description": "Free Qwen Coder model via OpenRouter.",
        "deployment": "Cloud API",
        "enabled": False
    },
    # NVIDIA NIM
    {
        "id": "nvidia_llama_3_1_405b",
        "provider_id": "nvidia_nim",
        "model_id": "meta/llama-3.1-405b-instruct",
        "display_name": "Llama 3.1 405B Instruct",
        "type": "API",
        "billing_mode": "RPM_RPD",
        "context_window": 128000,
        "max_output_tokens": 4096,
        "capabilities": ["reasoning", "research", "planning"],
        "tags": ["Reasoning", "Large"],
        "default_roles": ["Researcher", "Reasoner"],
        "description": "NVIDIA NIM hosted Llama 3.1 405B model for heavy reasoning tasks.",
        "deployment": "Cloud API",
        "enabled": False
    },
    {
        "id": "nvidia_nemotron_70b",
        "provider_id": "nvidia_nim",
        "model_id": "nvidia/llama-3.1-nemotron-70b-instruct",
        "display_name": "Llama 3.1 Nemotron 70B",
        "type": "API",
        "billing_mode": "RPM_RPD",
        "context_window": 128000,
        "max_output_tokens": 4096,
        "capabilities": ["reasoning", "planning", "chat"],
        "tags": ["Reasoning", "Instruction"],
        "default_roles": ["Planner", "General Chat"],
        "description": "NVIDIA custom Nemotron instruction tuned model.",
        "deployment": "Cloud API",
        "enabled": False
    },
    {
        "id": "nvidia_deepseek_r1",
        "provider_id": "nvidia_nim",
        "model_id": "deepseek-ai/deepseek-r1",
        "display_name": "DeepSeek R1 (NVIDIA)",
        "type": "API",
        "billing_mode": "RPM_RPD",
        "context_window": 65536,
        "max_output_tokens": 8192,
        "capabilities": ["reasoning", "math", "research"],
        "tags": ["Reasoning", "Math"],
        "default_roles": ["Reasoner", "Researcher"],
        "description": "DeepSeek R1 hosted on NVIDIA NIM.",
        "deployment": "Cloud API",
        "enabled": False
    },
    # Google AI Studio
    {
        "id": "google_gemini_2.5_flash",
        "provider_id": "google_ai_studio",
        "model_id": "gemini-2.5-flash",
        "display_name": "Gemini 2.5 Flash",
        "type": "API",
        "billing_mode": "RPM_RPD",
        "context_window": 1048576,
        "max_output_tokens": 8192,
        "capabilities": ["chat", "vision", "tool_use", "long_context"],
        "tags": ["Fast", "Multimodal", "Free Tier"],
        "default_roles": ["GUI Agent", "Planner"],
        "description": "Google's fast multimodal model with massive context window.",
        "deployment": "Cloud API",
        "enabled": False
    },
    {
        "id": "google_gemini_2.5_flash_lite",
        "provider_id": "google_ai_studio",
        "model_id": "gemini-2.5-flash-lite",
        "display_name": "Gemini 2.5 Flash Lite",
        "type": "API",
        "billing_mode": "RPM_RPD",
        "context_window": 1048576,
        "max_output_tokens": 8192,
        "capabilities": ["chat", "fast", "fallback"],
        "tags": ["Fast", "Cheap", "Free Tier"],
        "default_roles": ["Fallback", "General Chat"],
        "description": "Lightweight Gemini model optimized for cost and speed.",
        "deployment": "Cloud API",
        "enabled": False
    },
    # Mistral
    {
        "id": "mistral_nemo",
        "provider_id": "mistral",
        "model_id": "open-mistral-nemo",
        "display_name": "Mistral Nemo",
        "type": "API",
        "billing_mode": "TOKEN_BUDGET",
        "context_window": 128000,
        "max_output_tokens": 8192,
        "capabilities": ["chat", "summarization"],
        "tags": ["General", "Fast"],
        "default_roles": ["General Chat", "Writer"],
        "description": "12B parameter model built in collaboration with NVIDIA.",
        "deployment": "Cloud API",
        "enabled": False
    },
    {
        "id": "mistral_small",
        "provider_id": "mistral",
        "model_id": "mistral-small-latest",
        "display_name": "Mistral Small Latest",
        "type": "API",
        "billing_mode": "TOKEN_BUDGET",
        "context_window": 32000,
        "max_output_tokens": 8192,
        "capabilities": ["chat", "tool_use", "planning"],
        "tags": ["General", "Tool Use"],
        "default_roles": ["Planner", "Tool Use"],
        "description": "Optimized lightweight model for function calling.",
        "deployment": "Cloud API",
        "enabled": False
    },
    {
        "id": "mistral_codestral",
        "provider_id": "mistral",
        "model_id": "codestral-latest",
        "display_name": "Codestral Latest",
        "type": "API",
        "billing_mode": "TOKEN_BUDGET",
        "context_window": 32000,
        "max_output_tokens": 8192,
        "capabilities": ["coding", "code_review", "tool_use"],
        "tags": ["Coding"],
        "default_roles": ["Coder"],
        "description": "Mistral's premier model designed specifically for code generation.",
        "deployment": "Cloud API",
        "enabled": False
    },
    # ZenMux
    {
        "id": "zenmux_gemini_3_flash_preview_free",
        "provider_id": "zenmux",
        "model_id": "google/gemini-3-flash-preview-free",
        "display_name": "Gemini 3 Flash Preview Free",
        "type": "API",
        "billing_mode": "TOKEN_BUDGET",
        "context_window": 32000,
        "max_output_tokens": 8192,
        "capabilities": ["chat", "vision", "fast"],
        "tags": ["Free", "Fast", "Multimodal"],
        "default_roles": ["GUI Agent", "General Chat"],
        "description": "Free preview model of Gemini 3 Flash via ZenMux.",
        "deployment": "Cloud API",
        "enabled": False
    },
    {
        "id": "zenmux_mimo_v2_flash_free",
        "provider_id": "zenmux",
        "model_id": "xiaomi/mimo-v2-flash-free",
        "display_name": "Mimo v2 Flash Free",
        "type": "API",
        "billing_mode": "TOKEN_BUDGET",
        "context_window": 16384,
        "max_output_tokens": 4096,
        "capabilities": ["reasoning", "coding", "agent"],
        "tags": ["Free", "Reasoning", "Coding"],
        "default_roles": ["Coder", "Reasoner"],
        "description": "Free agentic model via ZenMux.",
        "deployment": "Cloud API",
        "enabled": False
    },
    {
        "id": "zenmux_glm_4_6v_flash_free",
        "provider_id": "zenmux",
        "model_id": "z-ai/glm-4.6v-flash-free",
        "display_name": "GLM 4.6V Flash Free",
        "type": "API",
        "billing_mode": "TOKEN_BUDGET",
        "context_window": 8192,
        "max_output_tokens": 4096,
        "capabilities": ["vision", "tool_use", "agent"],
        "tags": ["Free", "Vision", "Function Calling"],
        "default_roles": ["GUI Agent", "Tool Use"],
        "description": "Free multimodal/vision model via ZenMux.",
        "deployment": "Cloud API",
        "enabled": False
    },
    # NaraRouter
    {
        "id": "nararouter_free_default",
        "provider_id": "nararouter",
        "model_id": "nararouter/free-default",
        "display_name": "Nara Free Default",
        "type": "API",
        "billing_mode": "TOKEN_BUDGET",
        "context_window": 8192,
        "max_output_tokens": 4096,
        "capabilities": ["chat", "fast", "fallback"],
        "tags": ["Free", "Router"],
        "default_roles": ["Fallback"],
        "description": "Default free gateway model on NaraRouter.",
        "deployment": "Cloud API",
        "enabled": False
    },
    # BluesMinds
    {
        "id": "bluesminds_free_default",
        "provider_id": "bluesminds",
        "model_id": "bluesminds/free-default",
        "display_name": "BluesMinds Free Gateway",
        "type": "API",
        "billing_mode": "ONE_TIME_CREDIT",
        "context_window": 8192,
        "max_output_tokens": 4096,
        "capabilities": ["chat", "fast"],
        "tags": ["Free", "Gateway"],
        "default_roles": ["General Chat"],
        "description": "Free model endpoint gateway for BluesMinds.",
        "deployment": "Cloud API",
        "enabled": False
    },
    # AgentRouter
    {
        "id": "agentrouter_default",
        "provider_id": "agentrouter",
        "model_id": "agentrouter/default",
        "display_name": "AgentRouter Default Gateway",
        "type": "API",
        "billing_mode": "ONE_TIME_CREDIT",
        "context_window": 8192,
        "max_output_tokens": 4096,
        "capabilities": ["chat", "agent"],
        "tags": ["Agent", "Router"],
        "default_roles": ["General Chat"],
        "description": "Default router configuration for AgentRouter.",
        "deployment": "Cloud API",
        "enabled": False
    }
]
