"""Repository port for Production persistence."""

from __future__ import annotations

from typing import Any, Protocol

from windagent.kernel.events import EventEnvelope

from .models import (
    AssetRevisionRow,
    AudioTrackRow,
    CodeVideoProjectRow,
    EdlRow,
    MixPlanRow,
    ProductionAssetRow,
    ProductionProjectRow,
    ProductionRevisionRow,
    RenderJobRow,
)


class ProductionStore(Protocol):
    """Durable port — one method per aggregate table."""

    # -- projects ----------------------------------------------------------
    async def insert_project(self, row: ProductionProjectRow) -> bool: ...
    async def get_project(self, project_id: str) -> ProductionProjectRow | None: ...
    async def list_projects(self) -> tuple[ProductionProjectRow, ...]: ...
    async def update_project(
        self,
        project_id: str,
        *,
        title: str | None,
        description: str | None,
        status: str | None,
        current_revision_id: str | None,
        optimistic_version: int | None,
        expected_version: int | None,
        metadata_json: str | None,
    ) -> ProductionProjectRow | None: ...

    # -- revisions ---------------------------------------------------------
    async def insert_revision(self, row: ProductionRevisionRow) -> bool: ...
    async def get_revision(self, revision_id: str) -> ProductionRevisionRow | None: ...
    async def list_revisions(self, project_id: str | None = None) -> tuple[ProductionRevisionRow, ...]: ...
    async def update_revision(
        self,
        revision_id: str,
        *,
        status: str | None = None,
        locked: bool | None = None,
        optimistic_version: int | None = None,
        expected_version: int | None = None,
    ) -> ProductionRevisionRow | None: ...

    # -- assets ------------------------------------------------------------
    async def insert_asset(self, row: ProductionAssetRow) -> bool: ...
    async def get_asset(self, asset_id: str) -> ProductionAssetRow | None: ...
    async def list_assets(self, project_id: str | None = None) -> tuple[ProductionAssetRow, ...]: ...
    async def update_asset(
        self, asset_id: str, *, values: dict[str, Any]
    ) -> ProductionAssetRow | None: ...

    # -- asset revisions ---------------------------------------------------
    async def insert_asset_revision(self, row: AssetRevisionRow) -> bool: ...
    async def get_asset_revision(self, revision_id: str) -> AssetRevisionRow | None: ...
    async def list_asset_revisions(self, asset_id: str | None = None) -> tuple[AssetRevisionRow, ...]: ...

    # -- audio tracks ------------------------------------------------------
    async def insert_audio_track(self, row: AudioTrackRow) -> bool: ...
    async def get_audio_track(self, track_id: str) -> AudioTrackRow | None: ...
    async def list_audio_tracks(self, project_id: str | None = None) -> tuple[AudioTrackRow, ...]: ...
    async def update_audio_track(self, track_id: str, *, values: dict[str, Any]) -> AudioTrackRow | None: ...

    # -- mix plans ---------------------------------------------------------
    async def insert_mix_plan(self, row: MixPlanRow) -> bool: ...
    async def get_mix_plan(self, mix_plan_id: str) -> MixPlanRow | None: ...
    async def list_mix_plans(self, project_id: str | None = None) -> tuple[MixPlanRow, ...]: ...
    async def update_mix_plan(self, mix_plan_id: str, *, values: dict[str, Any]) -> MixPlanRow | None: ...

    # -- code video --------------------------------------------------------
    async def insert_code_video_project(self, row: CodeVideoProjectRow) -> bool: ...
    async def get_code_video_project(self, project_id: str) -> CodeVideoProjectRow | None: ...
    async def list_code_video_projects(self) -> tuple[CodeVideoProjectRow, ...]: ...
    async def update_code_video_project(
        self, project_id: str, *, values: dict[str, Any]
    ) -> CodeVideoProjectRow | None: ...

    # -- render jobs -------------------------------------------------------
    async def insert_render_job(self, row: RenderJobRow) -> bool: ...
    async def get_render_job(self, job_id: str) -> RenderJobRow | None: ...
    async def list_render_jobs(self, project_id: str | None = None) -> tuple[RenderJobRow, ...]: ...
    async def update_render_job(self, job_id: str, *, values: dict[str, Any]) -> RenderJobRow | None: ...

    # -- edls --------------------------------------------------------------
    async def insert_edl(self, row: EdlRow) -> bool: ...
    async def get_edl(self, edl_id: str) -> EdlRow | None: ...
    async def list_edls(self, project_id: str | None = None) -> tuple[EdlRow, ...]: ...
    async def update_edl(self, edl_id: str, *, values: dict[str, Any]) -> EdlRow | None: ...


class TransactionScope(Protocol):
    """Bounded UnitOfWork scope + outbox event writer."""

    def store(self) -> ProductionStore: ...
    async def record_event(self, envelope: EventEnvelope, *, deduplication_key: str | None = None) -> bool: ...
    async def commit(self) -> None: ...
    async def __aenter__(self) -> TransactionScope: ...
    async def __aexit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: object | None) -> bool: ...
