"""Durable agent-loop & budget repository port (Phase 2)."""

from __future__ import annotations

from typing import Any, Mapping, Protocol, runtime_checkable


@runtime_checkable
class AgentLoopRepositoryPort(Protocol):
    async def get_loop_state(self, agent_run_id: str) -> dict[str, Any] | None: ...
    async def create_loop_state(self, *, agent_run_id: str, state: str, limits: Mapping[str, Any], usage: Mapping[str, Any], scope: str, started_at: Any | None = None) -> dict[str, Any]: ...
    async def transition_loop_state(self, *, agent_run_id: str, expected_version: int, target_state: str, exhaustion_reason: str | None = None) -> dict[str, Any] | None: ...
    async def update_budget_usage(self, *, agent_run_id: str, expected_version: int, usage_patch: Mapping[str, Any], exhaustion_reason: str | None = None) -> dict[str, Any] | None: ...
    async def replace_budget_limits(self, *, agent_run_id: str, expected_version: int, limits: Mapping[str, Any], scope: str) -> dict[str, Any] | None: ...
    async def ensure_loop_state(self, *, agent_run_id: str, default_state: str = "CREATED", limits: Mapping[str, Any] | None = None, scope: str = "conversation") -> dict[str, Any]: ...

__all__ = ["AgentLoopRepositoryPort"]
