"""Agent Checkpoint repository port (Phase 5)."""
from __future__ import annotations
from typing import Any, Mapping, Protocol, runtime_checkable

@runtime_checkable
class AgentCheckpointRepositoryPort(Protocol):
    async def create_checkpoint(self, *, checkpoint_id: str, agent_run_id: str, kind: str, snapshot: Mapping[str, Any] | None = None, session_id: str | None = None, step_run_id: str | None = None, tool_name: str | None = None, fencing_token: str | None = None) -> dict[str, Any]: ...
    async def get_checkpoint(self, checkpoint_id: str) -> dict[str, Any] | None: ...
    async def list_checkpoints(self, agent_run_id: str, *, kind: str | None = None) -> list[dict[str, Any]]: ...
    async def latest_checkpoint(self, agent_run_id: str) -> dict[str, Any] | None: ...
    async def count_checkpoints(self, agent_run_id: str) -> int: ...

__all__ = ["AgentCheckpointRepositoryPort"]
