"""Delegation repository port (Phase 4)."""
from __future__ import annotations
from typing import Any, Mapping, Protocol, runtime_checkable
@runtime_checkable
class DelegationRepositoryPort(Protocol):
    async def create_delegation(self, *, child_agent_run_id: str, parent_agent_run_id: str, root_agent_run_id: str, delegation_depth: int, delegation_reason: str, failure_policy: str, allocated_budget: Mapping[str, Any] | None = None, bounded_context: Mapping[str, Any] | None = None) -> dict[str, Any]: ...
    async def get_delegation(self, child_agent_run_id: str) -> dict[str, Any] | None: ...
    async def get_delegation_by_child(self, child_agent_run_id: str) -> dict[str, Any] | None: ...
    async def list_children(self, parent_agent_run_id: str) -> list[dict[str, Any]]: ...
    async def list_tree(self, root_agent_run_id: str) -> list[dict[str, Any]]: ...
    async def publish_child_result(self, *, child_agent_run_id: str, expected_version: int, summary: Mapping[str, Any], artifact_refs: list[str] | tuple[str, ...]) -> dict[str, Any] | None: ...
    async def set_failure_policy(self, *, child_agent_run_id: str, expected_version: int, failure_policy: str) -> dict[str, Any] | None: ...
__all__ = ["DelegationRepositoryPort"]
