"""Persistent Goal repository port (Phase 5)."""
from __future__ import annotations
from typing import Any, Mapping, Protocol, runtime_checkable

@runtime_checkable
class PersistentGoalRepositoryPort(Protocol):
    async def create_goal(self, *, goal_id: str, objective: str, status: str = "ACTIVE", progress_summary: str = "", completion_criteria: Mapping[str, Any] | None = None, conversation_id: str | None = None, parent_task_id: str | None = None, agent_run_id: str | None = None, harness_version: str | None = None) -> dict[str, Any]: ...
    async def get_goal(self, goal_id: str) -> dict[str, Any] | None: ...
    async def list_goals(self, *, conversation_id: str | None = None, parent_task_id: str | None = None, status: str | None = None) -> list[dict[str, Any]]: ...
    async def update_progress(self, *, goal_id: str, expected_version: int, progress_summary: str) -> dict[str, Any] | None: ...
    async def transition_status(self, *, goal_id: str, expected_version: int, target_status: str, reason: str | None = None, blocked_reason: str | None = None) -> dict[str, Any] | None: ...
    async def update_completion_criteria(self, *, goal_id: str, expected_version: int, criteria: Mapping[str, Any]) -> dict[str, Any] | None: ...

__all__ = ["PersistentGoalRepositoryPort"]
