"""
WindAgent Studio contracts (studio.contract/v0.1).

Provider-neutral contract surface owned by Plan A: frozen IDs, typed errors,
durable task/event envelopes, application commands, capability profiles, and the
canonical port set shared by Plans A, B, and C.
"""

from windagent_core.contracts.studio.ids import (
    ArtifactId,
    EpisodeId,
    ProductionRevisionId,
    SeriesProjectId,
    StudioRunId,
)
from windagent_core.contracts.studio.errors import (
    HTTP_STATUS_BY_CODE,
    StudioApprovalRequiredError,
    StudioArtifactHashMismatchError,
    StudioCapabilityUnavailableError,
    StudioError,
    StudioErrorCode,
    StudioIdempotencyMismatchError,
    StudioInternalError,
    StudioInvalidTransitionError,
    StudioLockedRevisionError,
    StudioNotFoundError,
    StudioProviderUnavailableError,
    StudioStaleRevisionError,
    StudioValidationError,
)
from windagent_core.contracts.studio.models import (
    CONTRACT_VERSION,
    EVENT_SCHEMA_VERSION,
    TASK_ENVELOPE_SCHEMA_VERSION,
    TASK_RESULT_SCHEMA_VERSION,
    StudioArtifactRef,
    StudioEventEnvelope,
    StudioRouteProvenance,
    StudioTaskEnvelope,
    StudioTaskResult,
    StudioTaskStatus,
    StudioTaskType,
)
from windagent_core.contracts.studio.capabilities import (
    CapabilityKind,
    CapabilityStatus,
    RuntimeCapability,
    RuntimeCapabilityProfile,
)
from windagent_core.contracts.studio.commands import (
    CreateEpisodeCommand,
    CreateEpisodeResult,
    CreateSeriesCommand,
    CreateSeriesResult,
    DeriveRevisionCommand,
    DeriveRevisionResult,
    LockScreenplayCommand,
    LockScreenplayResult,
    RecordApprovalCommand,
    RecordApprovalResult,
    SelectIdeaCommand,
    SelectIdeaResult,
    StartRunCommand,
    StartRunResult,
    StudioCommand,
)
from windagent_core.contracts.studio.ports import (
    ApprovalRepositoryPort,
    EpisodeRepositoryPort,
    PreproductionModelPort,
    ProductionRevisionRepositoryPort,
    RuntimeCapabilityPort,
    SeriesProjectRepositoryPort,
    StoryArtifactRepositoryPort,
    StudioEventQueryPort,
    StudioRouteLockResult,
    StudioRunOrchestratorPort,
    StudioRunQueryPort,
    StudioTaskSubmissionPort,
    StudioUnitOfWorkPort,
)

__all__ = [
    "ArtifactId",
    "EpisodeId",
    "ProductionRevisionId",
    "SeriesProjectId",
    "StudioRunId",
    "HTTP_STATUS_BY_CODE",
    "StudioApprovalRequiredError",
    "StudioArtifactHashMismatchError",
    "StudioCapabilityUnavailableError",
    "StudioError",
    "StudioErrorCode",
    "StudioIdempotencyMismatchError",
    "StudioInternalError",
    "StudioInvalidTransitionError",
    "StudioLockedRevisionError",
    "StudioNotFoundError",
    "StudioProviderUnavailableError",
    "StudioStaleRevisionError",
    "StudioValidationError",
    "CONTRACT_VERSION",
    "EVENT_SCHEMA_VERSION",
    "TASK_ENVELOPE_SCHEMA_VERSION",
    "TASK_RESULT_SCHEMA_VERSION",
    "StudioArtifactRef",
    "StudioEventEnvelope",
    "StudioRouteProvenance",
    "StudioTaskEnvelope",
    "StudioTaskResult",
    "StudioTaskStatus",
    "StudioTaskType",
    "CapabilityKind",
    "CapabilityStatus",
    "RuntimeCapability",
    "RuntimeCapabilityProfile",
    "CreateEpisodeCommand",
    "CreateEpisodeResult",
    "CreateSeriesCommand",
    "CreateSeriesResult",
    "DeriveRevisionCommand",
    "DeriveRevisionResult",
    "LockScreenplayCommand",
    "LockScreenplayResult",
    "RecordApprovalCommand",
    "RecordApprovalResult",
    "SelectIdeaCommand",
    "SelectIdeaResult",
    "StartRunCommand",
    "StartRunResult",
    "StudioCommand",
    "ApprovalRepositoryPort",
    "EpisodeRepositoryPort",
    "PreproductionModelPort",
    "ProductionRevisionRepositoryPort",
    "RuntimeCapabilityPort",
    "SeriesProjectRepositoryPort",
    "StoryArtifactRepositoryPort",
    "StudioEventQueryPort",
    "StudioRouteLockResult",
    "StudioRunOrchestratorPort",
    "StudioRunQueryPort",
    "StudioTaskSubmissionPort",
    "StudioUnitOfWorkPort",
]
