"""
WindAgent Core Errors Package.
Exports all canonical exception classes and error hierarchy components.
"""

from windagent_core.errors.exceptions import (
    WindAgentError,
    DomainError,
    ValidationError,
    IdentityValidationError,
    ConflictError,
    InvalidStateTransitionError,
    TerminalStateMutationError,
    ConcurrentStateConflictError,
    NotFoundError,
    PermissionDeniedError,
    ApprovalRequiredError,
    ExecutionError,
    RuntimeLostError,
    ProviderError,
    RateLimitError,
    QuotaExhaustedError,
    AuthenticationError,
    TimeoutError,
    ToolError,
    SerializationError,
    IntegrityError,
    ConfigurationError,
    RetryableError,
    NonRetryableError,
    sanitize_error_details,
)

__all__ = [
    "WindAgentError",
    "DomainError",
    "ValidationError",
    "IdentityValidationError",
    "ConflictError",
    "InvalidStateTransitionError",
    "TerminalStateMutationError",
    "ConcurrentStateConflictError",
    "NotFoundError",
    "PermissionDeniedError",
    "ApprovalRequiredError",
    "ExecutionError",
    "RuntimeLostError",
    "ProviderError",
    "RateLimitError",
    "QuotaExhaustedError",
    "AuthenticationError",
    "TimeoutError",
    "ToolError",
    "SerializationError",
    "IntegrityError",
    "ConfigurationError",
    "RetryableError",
    "NonRetryableError",
    "sanitize_error_details",
]
