"""
Trusted deterministic scene build script — Blender 4.5 LTS (pinned).

Generated by the pinned scene compiler; read-only over scene_plan.json in the
current working directory (the job workspace). Never modified at runtime.
"""

import json
import math
import random
from pathlib import Path

plan = json.loads(Path("scene_plan.json").read_text(encoding="utf-8"))

import bpy  # noqa: E402  (bpy only exists inside blender)

random.seed(plan["seed"])


def _clear_scene():
    bpy.ops.wm.read_factory_settings(use_empty=True)


def _add_object(kind, name, location, rotation, scale):
    if kind == "CUBE":
        bpy.ops.mesh.primitive_cube_add(size=1.0)
    elif kind == "PLANE":
        bpy.ops.mesh.primitive_plane_add(size=1.0)
    else:
        bpy.ops.mesh.primitive_cube_add(size=1.0)
    obj = bpy.context.active_object
    obj.name = name
    obj.location = location
    obj.rotation_euler = rotation
    obj.scale = scale
    return obj


def _make_material(spec):
    mat = bpy.data.materials.new(name=spec["name"])
    mat.use_nodes = True
    bsdf = mat.node_tree.nodes.get("Principled BSDF")
    if bsdf is not None:
        bsdf.inputs["Base Color"].default_value = spec["base_color"]
        bsdf.inputs["Roughness"].default_value = spec["roughness"]
        bsdf.inputs["Metallic"].default_value = spec["metallic"]
    return mat


def _add_lights(specs):
    for light_spec in specs:
        bpy.ops.object.light_add(
            type=light_spec["kind"],
            location=light_spec["location"],
            rotation=light_spec["rotation"],
        )
        light = bpy.context.active_object
        light.name = light_spec["name"]
        light.data.energy = light_spec["energy"]
        light.data.color = light_spec["color"]


def _add_camera(spec):
    cam = bpy.data.cameras.new("MainCamera")
    cam.lens = spec["lens_mm"]
    cam.sensor_width = spec["sensor_width_mm"]
    obj = bpy.data.objects.new("MainCamera", cam)
    bpy.context.collection.objects.link(obj)
    obj.location = spec["location"]
    obj.rotation_euler = spec["rotation"]
    bpy.context.scene.camera = obj


def _animate(spec, frame_start, frame_end):
    target = bpy.data.objects.get(spec["target_object"])
    if target is None:
        return
    target.rotation_euler[2] = spec["start_rotation_z"]
    target.location = spec["start_location"]
    target.keyframe_insert(data_path="rotation_euler", frame=frame_start)
    target.keyframe_insert(data_path="location", frame=frame_start)
    target.rotation_euler[2] = spec["end_rotation_z"]
    target.location = spec["end_location"]
    target.keyframe_insert(data_path="rotation_euler", frame=frame_end)
    target.keyframe_insert(data_path="location", frame=frame_end)


def _configure_render(plan):
    scene = bpy.context.scene
    scene.frame_start = plan["frame_start"]
    scene.frame_end = plan["frame_end"]
    scene.render.fps = plan["fps"]
    scene.render.resolution_x = plan["resolution"]["width"]
    scene.render.resolution_y = plan["resolution"]["height"]
    scene.render.film_transparent = False
    scene.view_settings.view_transform = plan["color_management"]

    scene.render.engine = "CYCLES"
    cycles = scene.cycles
    cycles.samples = plan["cycles_samples"]
    cycles.use_denoising = plan["denoise"]
    if plan["device"] == "CPU":
        scene.cycles.device = "CPU"
    elif plan["device"] in ("OPTIX", "CUDA"):
        scene.cycles.device = "GPU"
        prefs = bpy.context.preferences.addons["cycles"].preferences
        prefs.compute_device_type = plan["device"]
        prefs.get_devices()
        for device in prefs.devices:
            device.use = device.type in ("OPTIX", "CUDA")


def main():
    _clear_scene()
    for obj_spec in plan["objects"]:
        obj = _add_object(
            obj_spec["kind"],
            obj_spec["name"],
            obj_spec["location"],
            obj_spec["rotation"],
            obj_spec["scale"],
        )
        obj.data.materials.append(_make_material(plan["material"]))
    _add_lights(plan["lights"])
    _add_camera(plan["camera"])
    _animate(plan["animation"], plan["frame_start"], plan["frame_end"])
    _configure_render(plan)
    out = Path(plan.get("output_blend_path", "scene.blend"))
    out.parent.mkdir(parents=True, exist_ok=True)
    bpy.ops.wm.save_as_mainfile(filepath=str(out))
    print(json.dumps({"built": True, "objects": len(plan["objects"]),
                      "lights": len(plan["lights"]), "out": str(out)}))


if __name__ == "__main__":
    main()

# plan-payload
_PLAN_PAYLOAD = '{"animation": {"end_frame": 24, "end_location": [0.0, 0.0, 1.0], "end_rotation_z": 6.283185307179586, "start_frame": 1, "start_location": [0.0, 0.0, 1.0], "start_rotation_z": 0.0, "target_object": "Cube"}, "camera": {"lens_mm": 35.0, "location": [7.0, -6.0, 4.5], "rotation": [1.1, 0.0, 0.7], "sensor_width_mm": 36.0}, "color_management": "Standard", "config_hash": "ee66ba95ece3c0a03ad0639d3bb7142a6f12102d766dfde78c817366f524f2da", "cycles_samples": 8, "denoise": false, "device": "CPU", "fps": 24, "frame_end": 24, "frame_start": 1, "input_hash": "7e695ef4c46f22bc23dd1d59916c354e6c589515ffc82d322fa5322d5cf2bdde", "lights": [{"color": [1.0, 1.0, 1.0], "energy": 800.0, "kind": "AREA", "location": [5.0, -4.0, 6.0], "name": "Key", "rotation": [0.0, 0.0, 0.0]}, {"color": [1.0, 1.0, 1.0], "energy": 200.0, "kind": "AREA", "location": [-5.0, -4.0, 3.0], "name": "Fill", "rotation": [0.0, 0.0, 0.0]}, {"color": [1.0, 1.0, 1.0], "energy": 300.0, "kind": "AREA", "location": [0.0, 6.0, 5.0], "name": "Rim", "rotation": [0.0, 0.0, 0.0]}], "material": {"base_color": [0.8, 0.2, 0.2, 1.0], "metallic": 0.0, "name": "SmokeMaterial", "roughness": 0.4}, "objects": [{"kind": "CUBE", "location": [0.0, 0.0, 0.5], "name": "Cube", "rotation": [0.0, 0.0, 0.0], "scale": [1.0, 1.0, 1.0]}, {"kind": "PLANE", "location": [0.0, 0.0, 0.0], "name": "Ground", "rotation": [0.0, 0.0, 0.0], "scale": [4.0, 4.0, 1.0]}], "output_blend_path": "scene.blend", "resolution": {"height": 360, "width": 640}, "scene_id": "scn_golden", "scene_plan_id": "sp_scn_golden", "schema_version": "1.0.0", "seed": 2120834804, "tool_hash": "7a1eda1d25e8d39d8f99f72e5aa7d32e3b0022c442dc526d1ac0476827dffe00"}'
