"""Repository port for Live Record persistence."""

from __future__ import annotations

from typing import Any, Protocol

from windagent.kernel.events import EventEnvelope

from .models import (
    DirectorSessionRow,
    LiveExecutionPlanRow,
    RecordingEventRow,
    RecordingSegmentRow,
    RecordingTakeRow,
)


class LiveRecordStore(Protocol):
    # -- plans -----------------------------------------------------------
    async def insert_plan(self, row: LiveExecutionPlanRow) -> bool: ...
    async def get_plan(self, plan_id: str) -> LiveExecutionPlanRow | None: ...
    async def list_plans(self, episode_id: str | None = None) -> tuple[LiveExecutionPlanRow, ...]: ...
    async def update_plan(
        self,
        plan_id: str,
        *,
        status: str | None = None,
        plan_hash: str | None = None,
        frozen_at: Any | None = None,
        scenes_json: str | None = None,
        actions_json: str | None = None,
        payload_bundles_json: str | None = None,
        source_workspace_hash: str | None = None,
        recording_profile_json: str | None = None,
        optimistic_version: int | None = None,
        expected_version: int | None = None,
        metadata_json: str | None = None,
    ) -> LiveExecutionPlanRow | None: ...
    async def next_preparation_revision(self, episode_id: str) -> int: ...

    # -- takes -----------------------------------------------------------
    async def insert_take(self, row: RecordingTakeRow) -> bool: ...
    async def get_take(self, take_id: str) -> RecordingTakeRow | None: ...
    async def list_takes(self, execution_plan_id: str | None = None) -> tuple[RecordingTakeRow, ...]: ...
    async def update_take(self, take_id: str, *, status: str | None = None, optimistic_version: int | None = None, expected_version: int | None = None) -> RecordingTakeRow | None: ...

    # -- segments --------------------------------------------------------
    async def insert_segment(self, row: RecordingSegmentRow) -> bool: ...
    async def upsert_segment(self, row: RecordingSegmentRow) -> RecordingSegmentRow: ...
    async def get_segment(self, segment_id: str) -> RecordingSegmentRow | None: ...
    async def list_segments(self, take_id: str) -> tuple[RecordingSegmentRow, ...]: ...

    # -- events ----------------------------------------------------------
    async def append_event(self, row: RecordingEventRow) -> RecordingEventRow: ...
    async def list_events(self, take_id: str) -> tuple[RecordingEventRow, ...]: ...

    # -- director sessions -----------------------------------------------
    async def insert_director_session(self, row: DirectorSessionRow) -> bool: ...
    async def get_director_session(self, session_id: str) -> DirectorSessionRow | None: ...
    async def update_director_session(self, session_id: str, *, connection_state: str | None = None, expires_at: Any | None = None, metadata_json: str | None = None) -> DirectorSessionRow | None: ...
    async def list_director_sessions(self, execution_plan_id: str | None = None) -> tuple[DirectorSessionRow, ...]: ...


class TransactionScope(Protocol):
    def store(self) -> LiveRecordStore: ...
    async def record_event(self, envelope: EventEnvelope, *, deduplication_key: str | None = None) -> bool: ...
    async def commit(self) -> None: ...
    async def __aenter__(self) -> TransactionScope: ...
    async def __aexit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: object | None) -> bool: ...
