"""Base Package for WindAgent Provider Subsystem V3.

Errors and capability profiles are owned here (implementation concern).
Canonical contracts (request/response/usage/capabilities/ports) live in
``windagent_core.contracts.providers`` and are re-exported for convenience.
"""

from windagent_providers.base.secret_redaction import redact_text, redact_dict
from windagent_providers.base.errors import (
    ProviderFailure,
    AuthenticationFailure,
    PermissionFailure,
    RateLimitFailure,
    QuotaExhaustedFailure,
    ModelNotFoundFailure,
    InvalidRequestFailure,
    ContextOverflowFailure,
    ContentPolicyFailure,
    ProviderUnavailableFailure,
    NetworkFailure,
    TimeoutFailure,
    ProtocolMismatchFailure,
    MalformedResponseFailure,
    CancellationFailure,
    SameModelEndpointExhausted,
)
from windagent_core.contracts.providers import (
    CacheDirective,
    CachePort,
    CanonicalModelRegistryPort,
    ConnectionTestResult,
    DiscoveredModel,
    EndpointRegistryPort,
    EndpointStatePort,
    FinishReason,
    ModelDescriptor,
    ProtocolDetectionResult,
    ProviderCapabilities,
    ProviderHealth,
    ProviderRequest,
    ProviderResponse,
    ProviderStreamEvent,
    ProviderUsage,
    QuotaState,
    QuotaStatePort,
    RateLimitState,
    RouteAttemptPort,
    RouteLockPort,
    UsageLedgerPort,
)
from windagent_providers.base.capabilities import (
    ModelCapability,
    ModelCapabilityProfile,
    KNOWN_MODEL_PROFILES,
)
from windagent_providers.base.provider import (
    BaseModelProvider,
    QuotaSnapshot,
    ModelChunk,
)

__all__ = [
    "redact_text",
    "redact_dict",
    "ProviderFailure",
    "AuthenticationFailure",
    "PermissionFailure",
    "RateLimitFailure",
    "QuotaExhaustedFailure",
    "ModelNotFoundFailure",
    "InvalidRequestFailure",
    "ContextOverflowFailure",
    "ContentPolicyFailure",
    "ProviderUnavailableFailure",
    "NetworkFailure",
    "TimeoutFailure",
    "ProtocolMismatchFailure",
    "MalformedResponseFailure",
    "CancellationFailure",
    "SameModelEndpointExhausted",
    "FinishReason",
    "CacheDirective",
    "ProviderUsage",
    "ProviderHealth",
    "QuotaState",
    "RateLimitState",
    "ProviderCapabilities",
    "ModelDescriptor",
    "DiscoveredModel",
    "ConnectionTestResult",
    "ProtocolDetectionResult",
    "ProviderRequest",
    "ProviderResponse",
    "ProviderStreamEvent",
    "EndpointRegistryPort",
    "CanonicalModelRegistryPort",
    "RouteLockPort",
    "RouteAttemptPort",
    "QuotaStatePort",
    "EndpointStatePort",
    "CachePort",
    "UsageLedgerPort",
    "ModelCapability",
    "ModelCapabilityProfile",
    "KNOWN_MODEL_PROFILES",
    "BaseModelProvider",
    "QuotaSnapshot",
    "ModelChunk",
]
